<?php


?>


<div class="ss-form-container"><div class="ss-header-image-container"><div class="ss-header-image-image"><div class="ss-header-image-sizer"></div></div></div>
<div class="ss-top-of-page"><div class="ss-form-heading"><h1 class="ss-form-title" dir="ltr">Website Assessment Tool</h1>
<div class="ss-form-desc ss-no-ignore-whitespace" dir="ltr">UNIVERSITY OF EASTERN AFRICA, BARATON</div>

</div></div>
<div class="ss-form"><form action="https://docs.google.com/a/ueab.ac.ke/forms/d/1GPLRRZntT_Y8bQ6WLNeU8XUKNliXm6wbZiK9zMORzAE/formResponse" method="POST" id="ss-form" target="_self" onsubmit=""><ol role="list" class="ss-question-list" style="padding-left: 0">
<div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-radio"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_2066575901"><div class="ss-q-title">1.What is your gender?
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>

<ul class="ss-choices" role="radiogroup" aria-label="1.What is your gender?  "><li class="ss-choice-item"><label><span class="ss-choice-item-control goog-inline-block"><input name="entry.1140745361" value="Male" id="group_1140745361_1" role="radio" class="ss-q-radio" aria-label="Male" type="radio"></span>
<span class="ss-choice-label">Male</span>
</label></li> <li class="ss-choice-item"><label><span class="ss-choice-item-control goog-inline-block"><input name="entry.1140745361" value="Female" id="group_1140745361_2" role="radio" class="ss-q-radio" aria-label="Female" type="radio"></span>
<span class="ss-choice-label">Female</span>
</label></li></ul>
<div class="error-message" id="2066575901_errorMessage"></div>
<div class="required-message">This is a required question</div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-radio"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_628247123"><div class="ss-q-title">2.What is your status?
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>

<ul class="ss-choices" role="radiogroup" aria-label="2.What is your status?  "><li class="ss-choice-item"><label><span class="ss-choice-item-control goog-inline-block"><input name="entry.61544535" value="student" id="group_61544535_1" role="radio" class="ss-q-radio" aria-label="student" type="radio"></span>
<span class="ss-choice-label">student</span>
</label></li> <li class="ss-choice-item"><label><span class="ss-choice-item-control goog-inline-block"><input name="entry.61544535" value="faculty" id="group_61544535_2" role="radio" class="ss-q-radio" aria-label="faculty" type="radio"></span>
<span class="ss-choice-label">faculty</span>
</label></li> <li class="ss-choice-item"><label><span class="ss-choice-item-control goog-inline-block"><input name="entry.61544535" value="staff" id="group_61544535_3" role="radio" class="ss-q-radio" aria-label="staff" type="radio"></span>
<span class="ss-choice-label">staff</span>
</label></li></ul>
<div class="error-message" id="628247123_errorMessage"></div>
<div class="required-message">This is a required question</div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-radio"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1366511615"><div class="ss-q-title">3.How often do you visit the UEAB website?
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>

<ul class="ss-choices" role="radiogroup" aria-label="3.How often do you visit the UEAB website?  "><li class="ss-choice-item"><label><span class="ss-choice-item-control goog-inline-block"><input name="entry.1938818563" value="Daily" id="group_1938818563_1" role="radio" class="ss-q-radio" aria-label="Daily" type="radio"></span>
<span class="ss-choice-label">Daily</span>
</label></li> <li class="ss-choice-item"><label><span class="ss-choice-item-control goog-inline-block"><input name="entry.1938818563" value="Twice in a week" id="group_1938818563_2" role="radio" class="ss-q-radio" aria-label="Twice in a week" type="radio"></span>
<span class="ss-choice-label">Twice in a week</span>
</label></li> <li class="ss-choice-item"><label><span class="ss-choice-item-control goog-inline-block"><input name="entry.1938818563" value="Once in a semester" id="group_1938818563_3" role="radio" class="ss-q-radio" aria-label="Once in a semester" type="radio"></span>
<span class="ss-choice-label">Once in a semester</span>
</label></li></ul>
<div class="error-message" id="1366511615_errorMessage"></div>
<div class="required-message">This is a required question</div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-select"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_2028541795"><div class="ss-q-title">Kindly rate the following attributes of a website in your opinion of service delivery and user satisfaction. Put a tick () alongside the option that is applicable to you in the spaces provided.
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr">Rate the statement using the 1- 5 point Likert scale provided where (5 = strongly agree, 4=agree, 3=neutral, 2=disagree, 1=strongly disagree).</div></label>
<select name="entry.2028541795" id="entry_2028541795" aria-label="Kindly rate the following attributes of a website in your opinion of service delivery and user satisfaction. Put a tick () alongside the option that is applicable to you in the spaces provided. Rate the statement using the 1- 5 point Likert scale provided where (5 = strongly agree, 4=agree, 3=neutral, 2=disagree, 1=strongly disagree). "><option value=""></option>
<option value="Option 1">Option 1</option></select>
<div class="required-message">This is a required question</div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-grid"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1040165198"><div class="ss-q-title">1.Usability of the website
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr">Rate the statement using the 1- 5 point Likert scale provided where (5 = strongly agree, 4=agree, 3=neutral, 2=disagree, 1=strongly disagree).</div></label>
<div>
<table cellpadding="5" cellspacing="0" border="0"><thead><tr><td class="ss-gridnumbers ss-gridrow-leftlabel"></td>
<td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">5</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">4</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">3</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">2</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">1</label></td></tr></thead>
<tbody><tr role="radiogroup" aria-label="It is easy to find my way to information from the homepage" aria-describedby="1040165198_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">It is easy to find my way to information from the homepage</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.698483743" value="5" id="group_698483743_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.698483743" value="4" id="group_698483743_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.698483743" value="3" id="group_698483743_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.698483743" value="2" id="group_698483743_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.698483743" value="1" id="group_698483743_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="I am able to accurately predict which section of the website contains the information that am looking for" aria-describedby="1040165198_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">I am able to accurately predict which section of the website contains the information that am looking for</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.932822648" value="5" id="group_932822648_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.932822648" value="4" id="group_932822648_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.932822648" value="3" id="group_932822648_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.932822648" value="2" id="group_932822648_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.932822648" value="1" id="group_932822648_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The homepage content makes me want to explore the site further" aria-describedby="1040165198_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The homepage content makes me want to explore the site further</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.730424561" value="5" id="group_730424561_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.730424561" value="4" id="group_730424561_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.730424561" value="3" id="group_730424561_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.730424561" value="2" id="group_730424561_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.730424561" value="1" id="group_730424561_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The website is well suited to first time visitors" aria-describedby="1040165198_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The website is well suited to first time visitors</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1270728517" value="5" id="group_1270728517_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1270728517" value="4" id="group_1270728517_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1270728517" value="3" id="group_1270728517_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1270728517" value="2" id="group_1270728517_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1270728517" value="1" id="group_1270728517_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="  The site has characteristics that make it appealing. " aria-describedby="1040165198_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">  The site has characteristics that make it appealing. </td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1886683382" value="5" id="group_1886683382_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1886683382" value="4" id="group_1886683382_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1886683382" value="3" id="group_1886683382_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1886683382" value="2" id="group_1886683382_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1886683382" value="1" id="group_1886683382_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr></tbody></table>
<div class="error-message" id="1040165198_errorMessage"></div>
<div class="required-message">Please enter one response per row</div></div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-grid"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1294258462"><div class="ss-q-title">2.Functionality of the Website
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<div>
<table cellpadding="5" cellspacing="0" border="0"><thead><tr><td class="ss-gridnumbers ss-gridrow-leftlabel"></td>
<td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">5</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">4</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">3</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">2</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">1</label></td></tr></thead>
<tbody><tr role="radiogroup" aria-label="The website contains administration tools which enhance efficiency i.e. Help, FAQ" aria-describedby="1294258462_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The website contains administration tools which enhance efficiency i.e. Help, FAQ</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.956711191" value="5" id="group_956711191_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.956711191" value="4" id="group_956711191_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.956711191" value="3" id="group_956711191_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.956711191" value="2" id="group_956711191_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.956711191" value="1" id="group_956711191_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="All functionality if clearly labeled" aria-describedby="1294258462_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">All functionality if clearly labeled</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1374479396" value="5" id="group_1374479396_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1374479396" value="4" id="group_1374479396_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1374479396" value="3" id="group_1374479396_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1374479396" value="2" id="group_1374479396_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1374479396" value="1" id="group_1374479396_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="It is easy to navigate the websitei.e. options to return to home page, top of pages is provided." aria-describedby="1294258462_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">It is easy to navigate the websitei.e. options to return to home page, top of pages is provided.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1050134585" value="5" id="group_1050134585_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1050134585" value="4" id="group_1050134585_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1050134585" value="3" id="group_1050134585_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1050134585" value="2" id="group_1050134585_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1050134585" value="1" id="group_1050134585_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="There are linkages to other sites that have discussions on similar topics" aria-describedby="1294258462_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">There are linkages to other sites that have discussions on similar topics</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1452118203" value="5" id="group_1452118203_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1452118203" value="4" id="group_1452118203_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1452118203" value="3" id="group_1452118203_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1452118203" value="2" id="group_1452118203_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1452118203" value="1" id="group_1452118203_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The selected graphics serve a functional purpose." aria-describedby="1294258462_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The selected graphics serve a functional purpose.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1476358134" value="5" id="group_1476358134_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1476358134" value="4" id="group_1476358134_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1476358134" value="3" id="group_1476358134_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1476358134" value="2" id="group_1476358134_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1476358134" value="1" id="group_1476358134_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr></tbody></table>
<div class="error-message" id="1294258462_errorMessage"></div>
<div class="required-message">Please enter one response per row</div></div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-grid"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_101571588"><div class="ss-q-title">3.Efficiency of the website
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<div>
<table cellpadding="5" cellspacing="0" border="0"><thead><tr><td class="ss-gridnumbers ss-gridrow-leftlabel"></td>
<td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">5</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">4</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">3</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">2</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">1</label></td></tr></thead>
<tbody><tr role="radiogroup" aria-label="I find it easy to use the website." aria-describedby="101571588_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">I find it easy to use the website.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.143790650" value="5" id="group_143790650_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.143790650" value="4" id="group_143790650_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.143790650" value="3" id="group_143790650_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.143790650" value="2" id="group_143790650_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.143790650" value="1" id="group_143790650_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The information posted on the website is always timely." aria-describedby="101571588_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The information posted on the website is always timely.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.518813420" value="5" id="group_518813420_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.518813420" value="4" id="group_518813420_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.518813420" value="3" id="group_518813420_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.518813420" value="2" id="group_518813420_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.518813420" value="1" id="group_518813420_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="I’m satisfied by the web content." aria-describedby="101571588_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">I’m satisfied by the web content.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.362852256" value="5" id="group_362852256_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.362852256" value="4" id="group_362852256_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.362852256" value="3" id="group_362852256_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.362852256" value="2" id="group_362852256_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.362852256" value="1" id="group_362852256_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The web services and functionalities are perfect." aria-describedby="101571588_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The web services and functionalities are perfect.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1065016337" value="5" id="group_1065016337_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1065016337" value="4" id="group_1065016337_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1065016337" value="3" id="group_1065016337_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1065016337" value="2" id="group_1065016337_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1065016337" value="1" id="group_1065016337_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The website offers dialogue areas or feedback features for visitors" aria-describedby="101571588_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The website offers dialogue areas or feedback features for visitors</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.340603343" value="5" id="group_340603343_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.340603343" value="4" id="group_340603343_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.340603343" value="3" id="group_340603343_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.340603343" value="2" id="group_340603343_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.340603343" value="1" id="group_340603343_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr></tbody></table>
<div class="error-message" id="101571588_errorMessage"></div>
<div class="required-message">Please enter one response per row</div></div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-grid"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_529057012"><div class="ss-q-title">4.Reliability of the website
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<div>
<table cellpadding="5" cellspacing="0" border="0"><thead><tr><td class="ss-gridnumbers ss-gridrow-leftlabel"></td>
<td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">5</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">4</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">3</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">2</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">1</label></td></tr></thead>
<tbody><tr role="radiogroup" aria-label="The website is accessible all the time." aria-describedby="529057012_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The website is accessible all the time.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.656677637" value="5" id="group_656677637_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.656677637" value="4" id="group_656677637_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.656677637" value="3" id="group_656677637_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.656677637" value="2" id="group_656677637_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.656677637" value="1" id="group_656677637_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The links work well." aria-describedby="529057012_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The links work well.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1977880859" value="5" id="group_1977880859_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1977880859" value="4" id="group_1977880859_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1977880859" value="3" id="group_1977880859_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1977880859" value="2" id="group_1977880859_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1977880859" value="1" id="group_1977880859_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The forms on the website are working " aria-describedby="529057012_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The forms on the website are working </td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.56155766" value="5" id="group_56155766_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.56155766" value="4" id="group_56155766_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.56155766" value="3" id="group_56155766_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.56155766" value="2" id="group_56155766_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.56155766" value="1" id="group_56155766_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The website contains some broken links." aria-describedby="529057012_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The website contains some broken links.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.564643399" value="5" id="group_564643399_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.564643399" value="4" id="group_564643399_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.564643399" value="3" id="group_564643399_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.564643399" value="2" id="group_564643399_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.564643399" value="1" id="group_564643399_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="Information on the website is regularly updated." aria-describedby="529057012_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">Information on the website is regularly updated.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.240856037" value="5" id="group_240856037_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.240856037" value="4" id="group_240856037_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.240856037" value="3" id="group_240856037_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.240856037" value="2" id="group_240856037_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.240856037" value="1" id="group_240856037_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr></tbody></table>
<div class="error-message" id="529057012_errorMessage"></div>
<div class="required-message">Please enter one response per row</div></div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-grid"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_98532631"><div class="ss-q-title">5.Availability of the website
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<div>
<table cellpadding="5" cellspacing="0" border="0"><thead><tr><td class="ss-gridnumbers ss-gridrow-leftlabel"></td>
<td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">5</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">4</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">3</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">2</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">1</label></td></tr></thead>
<tbody><tr role="radiogroup" aria-label="The website is available 24/7." aria-describedby="98532631_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The website is available 24/7.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1873264905" value="5" id="group_1873264905_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1873264905" value="4" id="group_1873264905_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1873264905" value="3" id="group_1873264905_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1873264905" value="2" id="group_1873264905_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1873264905" value="1" id="group_1873264905_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="I always get the information and services that I need from the website." aria-describedby="98532631_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">I always get the information and services that I need from the website.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.536894501" value="5" id="group_536894501_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.536894501" value="4" id="group_536894501_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.536894501" value="3" id="group_536894501_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.536894501" value="2" id="group_536894501_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.536894501" value="1" id="group_536894501_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="There is communication when the website is down." aria-describedby="98532631_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">There is communication when the website is down.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.825636449" value="5" id="group_825636449_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.825636449" value="4" id="group_825636449_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.825636449" value="3" id="group_825636449_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.825636449" value="2" id="group_825636449_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.825636449" value="1" id="group_825636449_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The website takes a very short time to load." aria-describedby="98532631_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The website takes a very short time to load.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1251666363" value="5" id="group_1251666363_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1251666363" value="4" id="group_1251666363_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1251666363" value="3" id="group_1251666363_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1251666363" value="2" id="group_1251666363_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1251666363" value="1" id="group_1251666363_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The network infrastructure in the institution is very good and so I can access the website from anywhere on campus." aria-describedby="98532631_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The network infrastructure in the institution is very good and so I can access the website from anywhere on campus.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1787591167" value="5" id="group_1787591167_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1787591167" value="4" id="group_1787591167_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1787591167" value="3" id="group_1787591167_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1787591167" value="2" id="group_1787591167_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1787591167" value="1" id="group_1787591167_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr></tbody></table>
<div class="error-message" id="98532631_errorMessage"></div>
<div class="required-message">Please enter one response per row</div></div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-grid"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1402638180"><div class="ss-q-title">6.Security of the website
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<div>
<table cellpadding="5" cellspacing="0" border="0"><thead><tr><td class="ss-gridnumbers ss-gridrow-leftlabel"></td>
<td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">5</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">4</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">3</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">2</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">1</label></td></tr></thead>
<tbody><tr role="radiogroup" aria-label="I’m aware of the security policies regarding information protection in the institution." aria-describedby="1402638180_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">I’m aware of the security policies regarding information protection in the institution.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.737785482" value="5" id="group_737785482_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.737785482" value="4" id="group_737785482_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.737785482" value="3" id="group_737785482_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.737785482" value="2" id="group_737785482_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.737785482" value="1" id="group_737785482_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="I believe that the website is well protected" aria-describedby="1402638180_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">I believe that the website is well protected</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1128184839" value="5" id="group_1128184839_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1128184839" value="4" id="group_1128184839_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1128184839" value="3" id="group_1128184839_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1128184839" value="2" id="group_1128184839_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1128184839" value="1" id="group_1128184839_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The website is protected from malicious attacks." aria-describedby="1402638180_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The website is protected from malicious attacks.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1587131609" value="5" id="group_1587131609_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1587131609" value="4" id="group_1587131609_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1587131609" value="3" id="group_1587131609_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1587131609" value="2" id="group_1587131609_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1587131609" value="1" id="group_1587131609_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The website protects unauthorized modification to information." aria-describedby="1402638180_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The website protects unauthorized modification to information.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1836292008" value="5" id="group_1836292008_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1836292008" value="4" id="group_1836292008_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1836292008" value="3" id="group_1836292008_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1836292008" value="2" id="group_1836292008_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1836292008" value="1" id="group_1836292008_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The website is secure so as to avoid loss of information" aria-describedby="1402638180_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The website is secure so as to avoid loss of information</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.208578871" value="5" id="group_208578871_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.208578871" value="4" id="group_208578871_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.208578871" value="3" id="group_208578871_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.208578871" value="2" id="group_208578871_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.208578871" value="1" id="group_208578871_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr></tbody></table>
<div class="error-message" id="1402638180_errorMessage"></div>
<div class="required-message">Please enter one response per row</div></div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-grid"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1079337781"><div class="ss-q-title">7.Service Quality(Quality of information)
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<div>
<table cellpadding="5" cellspacing="0" border="0"><thead><tr><td class="ss-gridnumbers ss-gridrow-leftlabel"></td>
<td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">5</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">4</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">3</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">2</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">1</label></td></tr></thead>
<tbody><tr role="radiogroup" aria-label="The content on the website is regularly updated" aria-describedby="1079337781_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The content on the website is regularly updated</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.246763967" value="5" id="group_246763967_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.246763967" value="4" id="group_246763967_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.246763967" value="3" id="group_246763967_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.246763967" value="2" id="group_246763967_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.246763967" value="1" id="group_246763967_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The information posted on the website is valid and accurate" aria-describedby="1079337781_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The information posted on the website is valid and accurate</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1088158322" value="5" id="group_1088158322_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1088158322" value="4" id="group_1088158322_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1088158322" value="3" id="group_1088158322_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1088158322" value="2" id="group_1088158322_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1088158322" value="1" id="group_1088158322_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The information presented is easy to understand" aria-describedby="1079337781_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The information presented is easy to understand</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1937500491" value="5" id="group_1937500491_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1937500491" value="4" id="group_1937500491_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1937500491" value="3" id="group_1937500491_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1937500491" value="2" id="group_1937500491_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1937500491" value="1" id="group_1937500491_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The content on the website is varied and changing (dynamic)" aria-describedby="1079337781_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">The content on the website is varied and changing (dynamic)</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.416263750" value="5" id="group_416263750_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.416263750" value="4" id="group_416263750_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.416263750" value="3" id="group_416263750_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.416263750" value="2" id="group_416263750_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.416263750" value="1" id="group_416263750_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="The website shows that the institution considers service quality." aria-describedby="1079337781_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">The website shows that the institution considers service quality.</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1967867590" value="5" id="group_1967867590_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1967867590" value="4" id="group_1967867590_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1967867590" value="3" id="group_1967867590_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1967867590" value="2" id="group_1967867590_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1967867590" value="1" id="group_1967867590_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr></tbody></table>
<div class="error-message" id="1079337781_errorMessage"></div>
<div class="required-message">Please enter one response per row</div></div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-grid"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_2000410039"><div class="ss-q-title">8.What weight would you assign to each of these attributes given the range of  1-5 where 5 is the most important and 1 the least important
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<div>
<table cellpadding="5" cellspacing="0" border="0"><thead><tr><td class="ss-gridnumbers ss-gridrow-leftlabel"></td>
<td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">5</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">4</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">3</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">2</label></td> <td class="ss-gridnumbers" style="width: 16%;"><label class="ss-gridnumber">1</label></td></tr></thead>
<tbody><tr role="radiogroup" aria-label="Usability" aria-describedby="2000410039_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">Usability</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.14959101" value="5" id="group_14959101_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.14959101" value="4" id="group_14959101_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.14959101" value="3" id="group_14959101_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.14959101" value="2" id="group_14959101_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.14959101" value="1" id="group_14959101_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="Functionality" aria-describedby="2000410039_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">Functionality</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.794051136" value="5" id="group_794051136_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.794051136" value="4" id="group_794051136_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.794051136" value="3" id="group_794051136_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.794051136" value="2" id="group_794051136_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.794051136" value="1" id="group_794051136_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="Reliability" aria-describedby="2000410039_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">Reliability</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.963907246" value="5" id="group_963907246_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.963907246" value="4" id="group_963907246_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.963907246" value="3" id="group_963907246_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.963907246" value="2" id="group_963907246_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.963907246" value="1" id="group_963907246_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="Efficiency" aria-describedby="2000410039_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">Efficiency</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.424405048" value="5" id="group_424405048_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.424405048" value="4" id="group_424405048_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.424405048" value="3" id="group_424405048_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.424405048" value="2" id="group_424405048_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.424405048" value="1" id="group_424405048_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="Security" aria-describedby="2000410039_errorMessage" class="ss-gridrow ss-grid-row-odd"><td class="ss-gridrow ss-gridrow-leftlabel">Security</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.263338026" value="5" id="group_263338026_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.263338026" value="4" id="group_263338026_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.263338026" value="3" id="group_263338026_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.263338026" value="2" id="group_263338026_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.263338026" value="1" id="group_263338026_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr> <tr role="radiogroup" aria-label="Availability" aria-describedby="2000410039_errorMessage" class="ss-gridrow ss-grid-row-even"><td class="ss-gridrow ss-gridrow-leftlabel">Availability</td>
<td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1983936454" value="5" id="group_1983936454_1" role="radio" class="ss-q-radio" aria-label="5" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1983936454" value="4" id="group_1983936454_2" role="radio" class="ss-q-radio" aria-label="4" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1983936454" value="3" id="group_1983936454_3" role="radio" class="ss-q-radio" aria-label="3" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1983936454" value="2" id="group_1983936454_4" role="radio" class="ss-q-radio" aria-label="2" type="radio"></div></label></td> <td class="ss-gridrow" style="width: 16%;"><label class="ss-grid-button-label"><div class="ss-grid-button-wrapper"><input name="entry.1983936454" value="1" id="group_1983936454_5" role="radio" class="ss-q-radio" aria-label="1" type="radio"></div></label></td></tr></tbody></table>
<div class="error-message" id="2000410039_errorMessage"></div>
<div class="required-message">Please enter one response per row</div></div></div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-paragraph-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1549723820"><div class="ss-q-title">9.In your own opinions what improvements would you want to see on the university website?
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<textarea name="entry.1549723820" rows="8" cols="0" class="ss-q-long" id="entry_1549723820" dir="auto" aria-label="9.In your own opinions what improvements would you want to see on the university website?  "></textarea>
<div class="error-message" id="562340613_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-paragraph-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1811719953"><div class="ss-q-title">10.In your opinion is there any other attribute(parameters) that you think should be considered in evaluating the institutions website?
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<textarea name="entry.1811719953" rows="8" cols="0" class="ss-q-long" id="entry_1811719953" dir="auto" aria-label="10.In your opinion is there any other attribute(parameters) that you think should be considered in evaluating the institutions website?  "></textarea>
<div class="error-message" id="382732590_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-paragraph-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_2028068815"><div class="ss-q-title">11.Is there any services that you would wish  was offered by the website?
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<textarea name="entry.2028068815" rows="8" cols="0" class="ss-q-long" id="entry_2028068815" dir="auto" aria-label="11.Is there any services that you would wish  was offered by the website?  "></textarea>
<div class="error-message" id="237910313_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div>
<input name="draftResponse" value="[,,&quot;-4516145101190162283&quot;]
" type="hidden">
<input name="pageHistory" value="0" type="hidden">


<input name="fbzx" value="-4516145101190162283" type="hidden">

<div class="ss-item ss-navigate"><table id="navigation-table"><tbody><tr><td class="ss-form-entry goog-inline-block" id="navigation-buttons" dir="ltr">
<input name="submit" value="Submit" id="ss-submit" type="submit">
<div class="ss-password-warning ss-secondary-text">Never submit passwords through Google Forms.</div></td>
</tr></tbody></table></div></ol></form></div>
<div class="ss-footer"><div class="ss-attribution"></div>
<div class="ss-legal"><div class="disclaimer-separator"></div>
<div class="disclaimer" dir="ltr"><div class="powered-by-logo"><span class="powered-by-text">Powered by</span>
<a href="https://www.google.com/forms/about/?utm_source=product&amp;utm_medium=forms_logo&amp;utm_campaign=forms"><div class="ss-logo-container ss-logo-css-container"><div class="ss-logo-image"></div>
<span class="aria-only-help">Google Forms</span></div></a></div>
<div class="ss-terms"><span class="disclaimer-msg">This form was created inside of UNIVERSITY OF EASTERN AFRICA, BARATON.</span>
<br>
<a href="https://docs.google.com/forms/d/1GPLRRZntT_Y8bQ6WLNeU8XUKNliXm6wbZiK9zMORzAE/reportabuse?source=https://docs.google.com/a/ueab.ac.ke/forms/d/1GPLRRZntT_Y8bQ6WLNeU8XUKNliXm6wbZiK9zMORzAE/viewform?c%3D0%26w%3D1%26usp%3Dmail_form_link">Report Abuse</a>
-
<a href="http://www.google.com/accounts/TOS">Terms of Service</a>
-
<a href="http://www.google.com/google-d-s/terms.html">Additional Terms</a></div></div></div></div>

<div id="docs-aria-speakable" class="docs-a11y-ariascreenreader-speakable docs-offscreen" aria-live="assertive" role="region" aria-atomic="">Screen reader support enabled. </div></div>